"""change invitation message to varchar 20

Revision ID: 2888419d448f
Revises: c98a94a8118d
Create Date: 2025-11-17 12:27:50.857063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2888419d448f'
down_revision: Union[str, None] = 'c98a94a8118d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invitations', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index('ix_invitations_is_active', table_name='invitations')
    op.drop_column('invitations', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('ix_invitations_is_active', 'invitations', ['is_active'], unique=False)
    op.alter_column('invitations', 'message',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
