"""add color_hex to tags, make nullable

Revision ID: 6c55ae81dd58
Revises: e2e9ac7bf9f6
Create Date: 2025-10-14 17:07:19.248538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c55ae81dd58'
down_revision: Union[str, None] = 'e2e9ac7bf9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag_categories', 'color_hex',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tag_categories', 'display_order')
    op.add_column('tags', sa.Column('color_hex', sa.String(), nullable=True))
    op.drop_column('tags', 'display_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tags', 'color_hex')
    op.add_column('tag_categories', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('tag_categories', 'color_hex',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
