"""Initial migration

Revision ID: 9f63823cac97
Revises: 
Create Date: 2025-10-09 03:05:41.903724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f63823cac97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='전시 제목'),
    sa.Column('description', sa.Text(), nullable=True, comment='전시 설명'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='전시 장소'),
    sa.Column('poster_url', sa.String(length=500), nullable=True, comment='전시 포스터 이미지 URL (S3)'),
    sa.Column('artist_names', sa.ARRAY(sa.String()), nullable=True, comment='참여 작가 이름 리스트'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='전시 시작일'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='전시 종료일'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성 일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='수정 일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibitions_id'), 'exhibitions', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='태그 이름'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='사용자 고유 식별자 (UUID)'),
    sa.Column('user_type', sa.Enum('VISITOR', 'ARTIST', name='usertype'), nullable=False, comment='사용자 타입 (관람객/작가)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성 일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='수정 일시'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='사용자 이름 (선택)'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='이메일 (선택)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('artworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='작품 제목'),
    sa.Column('artist_name', sa.String(length=100), nullable=False, comment='작가 이름'),
    sa.Column('description', sa.Text(), nullable=True, comment='작품 설명'),
    sa.Column('year', sa.Integer(), nullable=True, comment='제작 연도'),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='작품 원본 이미지 URL (S3)'),
    sa.Column('exhibition_id', sa.Integer(), nullable=False, comment='전시 ID'),
    sa.ForeignKeyConstraint(['exhibition_id'], ['exhibitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artworks_id'), 'artworks', ['id'], unique=False)
    op.create_table('visit_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('exhibition_id', sa.Integer(), nullable=False, comment='전시 ID'),
    sa.Column('visited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='방문 일시'),
    sa.ForeignKeyConstraint(['exhibition_id'], ['exhibitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_histories_id'), 'visit_histories', ['id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False, comment='관람객이 촬영한 작품 사진 URL (S3)'),
    sa.Column('text_review', sa.Text(), nullable=True, comment='텍스트 평가 (선택)'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('artwork_id', sa.Integer(), nullable=False, comment='작품 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='생성 일시'),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_table('review_tags',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_tags')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_visit_histories_id'), table_name='visit_histories')
    op.drop_table('visit_histories')
    op.drop_index(op.f('ix_artworks_id'), table_name='artworks')
    op.drop_table('artworks')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_exhibitions_id'), table_name='exhibitions')
    op.drop_table('exhibitions')
    # ### end Alembic commands ###
