"""create invitations table

Revision ID: c98a94a8118d
Revises: a55ffd0a7764
Create Date: 2025-11-17 12:06:31.137681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98a94a8118d'
down_revision: Union[str, None] = 'a55ffd0a7764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('exhibition_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exhibition_id'], ['exhibitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_artist_id'), 'invitations', ['artist_id'], unique=False)
    op.create_index(op.f('ix_invitations_code'), 'invitations', ['code'], unique=True)
    op.create_index(op.f('ix_invitations_exhibition_id'), 'invitations', ['exhibition_id'], unique=False)
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_index(op.f('ix_invitations_is_active'), 'invitations', ['is_active'], unique=False)
    op.drop_index('ix_artist_reaction_emojis_reaction_id', table_name='artist_reaction_emojis')
    op.drop_index('artworks_embedding_idx', table_name='artworks', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_constraint('devices_device_token_key', 'devices', type_='unique')
    op.drop_index('idx_devices_artist_id', table_name='devices')
    op.drop_index('idx_devices_is_active', table_name='devices')
    op.drop_index('idx_devices_visitor_id', table_name='devices')
    op.create_index(op.f('ix_devices_device_token'), 'devices', ['device_token'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.drop_constraint('devices_visitor_id_fkey', 'devices', type_='foreignkey')
    op.drop_constraint('devices_artist_id_fkey', 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'visitors', ['visitor_id'], ['id'])
    op.create_foreign_key(None, 'devices', 'artists', ['artist_id'], ['id'])
    op.drop_column('devices', 'app_version')
    op.drop_column('devices', 'device_type')
    op.add_column('visit_histories', sa.Column('invitation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'visit_histories', 'invitations', ['invitation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit_histories', type_='foreignkey')
    op.drop_column('visit_histories', 'invitation_id')
    op.add_column('devices', sa.Column('device_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('app_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key('devices_artist_id_fkey', 'devices', 'artists', ['artist_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('devices_visitor_id_fkey', 'devices', 'visitors', ['visitor_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_token'), table_name='devices')
    op.create_index('idx_devices_visitor_id', 'devices', ['visitor_id'], unique=False)
    op.create_index('idx_devices_is_active', 'devices', ['is_active'], unique=False)
    op.create_index('idx_devices_artist_id', 'devices', ['artist_id'], unique=False)
    op.create_unique_constraint('devices_device_token_key', 'devices', ['device_token'])
    op.create_index('artworks_embedding_idx', 'artworks', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('ix_artist_reaction_emojis_reaction_id', 'artist_reaction_emojis', ['reaction_id'], unique=False)
    op.drop_index(op.f('ix_invitations_is_active'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_exhibition_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_code'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_artist_id'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
